general:
    run_function_diagnostics: False                                        # Runs diagnostics on all functions except logging functions

logger:
    main_delay:               0.05                                         # Delay [sec] for the run() function of thread
    log_file_path:            /home/leon/Work_and_study/Space_Mission_Training/PH549 # Where to save logging files
    run_logger_diagnostics:   False                                        # Runs diagnostics on logging functions
    log_file_verbose:         False                                        # Will print to console the logging activity
    
serial_communication:
    main_delay:               0.05                                         # Delay [sec] for the run() function of thread
    default_baud_rate:        115200                                       # Buadrate of serial communication
    default_timeout:          3                                            # Timeout [sec] of serial communication

command_and_control:
    buffering_delay:          0                                            # Delay [sec] for different commanding operations
    que_data_delay:           3                                            # Delay [sec] for queuing new round of data

