general:
    run_function_diagnostics: False                                        # Runs diagnostics on all functions except logging functions

logger:
    main_delay:                   0.05                                     # Delay [sec] for the run() function of thread
    log_file_path_Linux:          logs/                                    # Where to save logging files on Linux system
    log_file_path_Windows:        C:\Users\Daniel_2\Desktop\Test_log_files # Where to save logging files on Windows (lab)
    log_file_path_mac:            /Users/taran/Test_log_files              # Where to save logging files on Mac (lab)
    run_logger_diagnostics:       False                                    # Runs diagnostics on logging functions
    log_file_verbose:             True                                     # Will print to console the logging activity
    
serial_communication:
    main_delay:                   0.05                                     # Delay [sec] for the run() function of thread
    default_baud_rate:            115200                                   # Buadrate of serial communication
    default_timeout:              8                                        # Timeout [sec] of serial communication

system_control:
    main_delay:                   3                                        # Delay [sec] for the run() function of thread
    buffering_delay:              0                                        # Delay [sec] for different commanding operations
    cutoff_time_high:             5                                        # Time [sec] the cutoff pin will be triggered
    cutoff_BCM_pin_number:        18                                       # The pin number in BCM layout of the cutoff relay
    cut_conditions:                                                        # Conditions which if met or exceeded will cut the payload
        gps_lat:                                                           # GPS Latitude [deg] limits for payload cutoff
            -                     1
            -                     2
        gps_lon:                                                           # GPS Longitude [deg] limits for payload cutoff
            -                     3
            -                     4
        gps_altitude:                                                      # Altitude [km] limit for payload cutoff
            -                     12345
        time:                                                              # Clock time which will trigger cutoff
            -                     "22:22"
telemetry:
    main_delay:                   0.5                                      # Delay [sec] for the run() function of thread
    buffering_delay:              0                                        # Delay [sec] for different commanding operations
    data_downlink_delay:          9                                        # Delay [sec] for sending down data through telemetry
    enable_telemetry:             True                                     # Turns Pi side of telemetry on/off

command_and_control:
    buffering_delay:              0                                        # Delay [sec] for different commanding operations
    que_data_delay:               3                                        # Delay [sec] for queuing new round of data
