general:
    run_function_diagnostics: False                                        # Runs diagnostics on all functions except logging functions

logger:
    main_delay:                   0.05                                     # Delay [sec] for the run() function of thread
    log_file_path_Linux:          /home/pi/RMC549Repos/RMC549_Group1/Flight_Software_Package/logs/ # Where to save logging files on Linux system
    log_file_path_Windows:        C:\Users\Daniel_2\Desktop\Test_log_files # Where to save logging files on Windows (lab)
    log_file_path_mac:            /Users/taran/Test_log_files              # Where to save logging files on Mac (lab)
    run_logger_diagnostics:       False                                    # Runs diagnostics on logging functions
    log_file_verbose:             True                                     # Will print to console the logging activity
    
serial_communication:
    main_delay:                   0.05                                     # Delay [sec] for the run() function of thread
    default_baud_rate:            115200                                   # Buadrate of serial communication
    default_timeout:              8                                        # Timeout [sec] of serial communication
    reconnection_wait:            5                                        # Delay [sec] to wait before reset on com fail
    arduino_reset_pin:            23                                       # BCM pin to reset arduino (if applicable)

system_control:
    main_delay:                   3                                        # Delay [sec] for the run() function of thread
    buffering_delay:              0                                        # Delay [sec] for different commanding operations
    cutoff_time_high:             5                                        # Time [sec] the cutoff pin will be triggered
    cutoff_BCM_pin_number:        18                                       # The pin number in BCM layout of the cutoff relay
    cut_conditions:                                                        # Conditions which if met or exceeded will cut the payload
        gps_lat:                                                           # GPS Latitude [deg] limits for payload cutoff
            -                     44.226650
            -                     44.235380
        gps_lon:                                                           # GPS Longitude [deg] limits for payload cutoff
            -                     -76.455131
            -                     -76.471524
        gps_altitude:                                                      # Altitude [km] limit for payload cutoff
            -                     25
        time:                                                              # UTC which will trigger cutoff. Assumes same day.
            -                     "14:10"
telemetry:
    main_delay:                   0.5                                      # Delay [sec] for the run() function of thread
    buffering_delay:              0                                        # Delay [sec] for different commanding operations
    data_downlink_delay:          9                                        # Delay [sec] for sending down data through telemetry
    enable_telemetry:             True                                     # Turns Pi side of telemetry on/off

command_and_control:
    buffering_delay:              0                                        # Delay [sec] for different commanding operations
    que_data_delay:               3                                        # Delay [sec] for queuing new round of data
